### ISSUE TITLE
eve-traders-handbook doesn't work currently on Xampp

### ISSUE THREAD

**Issue by Haroldyolo** [matthewpennell/eve-traders-handbook#14] opened 2016-05-20 22:11 UTC
Hi Matthew,

I spend the last 6 hours trying to install the app, but sadly without luck. I tried every possible solution (to my knowledge), but my vhost keep returning blank (white) page. Things I've checked:

1) Using last version of Xampp from their webpage, running windows 10
2) Ports are all the same everywhere and not blocked.
3) Database created/files imported without a single error
4) database set up to work with my acc name,.database name and password
5) vhost file edited and hosts file in windows edited with 127.0.0.1 to redirect to my vhost fake domain
6) Tried making both dummy index.txt and php test file inside /public folder to check if it works and both does. 

I am starting to thing that the problem is inside your index.php or something else within your files, but with my very low knowledge of php I cannot debuf it.

Please can you look into this and help if possible

Kind Regards.

**Comment by matthewpennell** [comment] 2016-05-21 17:11
Hi,

Thanks for letting me know. I develop on a Mac, so my knowledge of the most recent XAMPP releases is limited. I'll try a fresh install on Windows and see if I can figure out what the root cause of the problem you're having might be.

**Comment by matthewpennell** [comment] 2016-05-22 10:43
I've been able to successfully get ETH running on XAMPP on Windows, after a little bit of fiddling. I think the root cause of the problem is that Windows doesn't come with git installed, and even when you install it you don't get the right ssh support out of the box to allow you to clone repositories from Github. You can work around it by downloading the zip archive instead and copying it into htdocs under the C:\xampp install folder. Everything else pretty much works as normal.

I've updated the [installation instructions](https://github.com/matthewpennell/eve-traders-handbook/wiki/Installation) with a few new comments that relate specifically to working with XAMPP. Let me know if you continue to have problems.

**Comment by matthewpennell** [comment] 2016-05-22 10:45
Regarding your comments about default index.txt and index.php files working, what you can try is to watch the output in app/storage/logs/laravel.log - that file should have all error messages generated by the app, so try loading the normal index.php and see what errors are generated.

**Comment by Haroldyolo** [comment] 2016-05-22 11:14
Hi Matthew,

Thanks a lot for looking into this. I've tried again now and the outcome is the same. Here is the error from laravel.log:

`[2016-05-22 11:11:54] production.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148
Stack trace:
#0 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1049): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1017): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\xampp\htdocs\eve-traders-handbook\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\xampp\htdocs\eve-traders-handbook\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\eve-traders-handbook\public\index.php(49): Illuminate\Foundation\Application->run()
#11 {main} [] []
`

**Comment by Haroldyolo** [comment] 2016-05-22 13:24
I just did new install of xampp and it's working now, again thanks a lot for taking the time to double check it for me! I appreciate it

**Comment by Haroldyolo** [comment] 2016-05-22 13:37
New Problem sadly, when paste http://localhost:8888/eve-traders-handbook/import/zkillboard in order to import kills it returns error: Object not found! Error 404. I haven't selected any alliances in my region could that be the case why? I would like to see all the kills if possible that's why I haven't selected any.

**Comment by matthewpennell** [comment] 2016-05-22 13:57
Yes, you have to select one or more alliances - that's the way zkillboard's API works. I can patch it to work with no alliances possibly, but right now you need to enter at least one.

**Comment by Haroldyolo** [comment] 2016-05-22 14:01
Weird I just selected few alliances (the top ones from dotlan), but still returns error Object not found! Error 404. Mind you my Region (Heimatar) doesn't have any alliances. Is it too much of a hasle to make it work without selected alliances and just to import all kills in the region? I am ingame btw, if you wanna chat there in your channel.

**Comment by matthewpennell** [comment] 2016-05-22 15:27
Closing issue - problem was using CSV files instead of SQL dumps.

**Closed as completed by matthewpennell** 2016-05-22 15:27 UTC
